# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install termsteel -y
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Uninstall PyJWT
      run: |
        pip uninstall PyJWT -y
    - name: Uninstall PyJWT
      run: |
        pip install PyJWT==1.6.4 -y
    - name: Test 
      run: |
        termsteel
